[FILTER]
    Name                  rewrite_tag
    Match                 provost.raw
    Rule                  ident ^provost_.*_access$ provost.access true
    Rule                  message .*PROVOST_AUDIT_ERROR.* provost.error true

[FILTER]
    Name                  rewrite_tag
    Match                 provost.direct
    Rule                  $log_type ^access$ provost.access false
    Rule                  $log_type ^error$ provost.error false
    Emitter_Name          direct_audit
