[FILTER]
    Name                  rewrite_tag
    Match                 provost.raw
    Rule                  ident ^provost_.*_access$ provost.access true
    Rule                  message .*PROVOST_AUDIT_ERROR.* provost.error true
