[FILTER]
    Name                  aws
    Match                 provost.*
    imds_version          v2

[FILTER]
    Name                  record_modifier
    Match                 provost.*
    Record                Region ${AWS_REGION}
    Record                Instance_ID ${INSTANCE_ID}

[FILTER]
    Name                  modify
    Match                 provost.*
    Copy                  ident stream_tag
    Copy                  ec2_instance_id Instance_ID

[FILTER]
    Name                  record_modifier
    Match                 provost.access
    Record                log_type access

[FILTER]
    Name                  record_modifier
    Match                 provost.error
    Record                log_type error
