[FILTER]
    Name          rewrite_tag
    Match         provost.access
    Rule          $log_type ^access$ provost.local.access true
    Emitter_Name  local_access

[FILTER]
    Name          rewrite_tag
    Match         provost.error
    Rule          $log_type ^error$ provost.local.error true
    Emitter_Name  local_error

[FILTER]
    Name          lua
    Match         provost.local.*
    Script        /fluent-bit/etc/lua/encode_record.lua
    Call          encode_record