[FILTER]
    Name          rewrite_tag
    Match         provost.access
    Rule          $time_local ^(\d{2})/Jan/(\d{4}):(\d{2}):.*$ $TAG.$2.01.$1.$3 false
    Rule          $time_local ^(\d{2})/Feb/(\d{4}):(\d{2}):.*$ $TAG.$2.02.$1.$3 false
    Rule          $time_local ^(\d{2})/Mar/(\d{4}):(\d{2}):.*$ $TAG.$2.03.$1.$3 false
    Rule          $time_local ^(\d{2})/Apr/(\d{4}):(\d{2}):.*$ $TAG.$2.04.$1.$3 false
    Rule          $time_local ^(\d{2})/May/(\d{4}):(\d{2}):.*$ $TAG.$2.05.$1.$3 false
    Rule          $time_local ^(\d{2})/Jun/(\d{4}):(\d{2}):.*$ $TAG.$2.06.$1.$3 false
    Rule          $time_local ^(\d{2})/Jul/(\d{4}):(\d{2}):.*$ $TAG.$2.07.$1.$3 false
    Rule          $time_local ^(\d{2})/Aug/(\d{4}):(\d{2}):.*$ $TAG.$2.08.$1.$3 false
    Rule          $time_local ^(\d{2})/Sep/(\d{4}):(\d{2}):.*$ $TAG.$2.09.$1.$3 false
    Rule          $time_local ^(\d{2})/Oct/(\d{4}):(\d{2}):.*$ $TAG.$2.10.$1.$3 false
    Rule          $time_local ^(\d{2})/Nov/(\d{4}):(\d{2}):.*$ $TAG.$2.11.$1.$3 false
    Rule          $time_local ^(\d{2})/Dec/(\d{4}):(\d{2}):.*$ $TAG.$2.12.$1.$3 false
    Emitter_Name  re_emitted_access

[FILTER]
    Name          rewrite_tag
    Match         provost.error
    Rule          $message .*\"time_local\":\"(\d{2})/Jan/(\d{4}):(\d{2}):.* $TAG.$2.01.$1.$3 false
    Rule          $message .*\"time_local\":\"(\d{2})/Feb/(\d{4}):(\d{2}):.* $TAG.$2.02.$1.$3 false
    Rule          $message .*\"time_local\":\"(\d{2})/Mar/(\d{4}):(\d{2}):.* $TAG.$2.03.$1.$3 false
    Rule          $message .*\"time_local\":\"(\d{2})/Apr/(\d{4}):(\d{2}):.* $TAG.$2.04.$1.$3 false
    Rule          $message .*\"time_local\":\"(\d{2})/May/(\d{4}):(\d{2}):.* $TAG.$2.05.$1.$3 false
    Rule          $message .*\"time_local\":\"(\d{2})/Jun/(\d{4}):(\d{2}):.* $TAG.$2.06.$1.$3 false
    Rule          $message .*\"time_local\":\"(\d{2})/Jul/(\d{4}):(\d{2}):.* $TAG.$2.07.$1.$3 false
    Rule          $message .*\"time_local\":\"(\d{2})/Aug/(\d{4}):(\d{2}):.* $TAG.$2.08.$1.$3 false
    Rule          $message .*\"time_local\":\"(\d{2})/Sep/(\d{4}):(\d{2}):.* $TAG.$2.09.$1.$3 false
    Rule          $message .*\"time_local\":\"(\d{2})/Oct/(\d{4}):(\d{2}):.* $TAG.$2.10.$1.$3 false
    Rule          $message .*\"time_local\":\"(\d{2})/Nov/(\d{4}):(\d{2}):.* $TAG.$2.11.$1.$3 false
    Rule          $message .*\"time_local\":\"(\d{2})/Dec/(\d{4}):(\d{2}):.* $TAG.$2.12.$1.$3 false
    Rule          $time_local ^(\d{2})/Jan/(\d{4}):(\d{2}):.*$ $TAG.$2.01.$1.$3 false
    Rule          $time_local ^(\d{2})/Feb/(\d{4}):(\d{2}):.*$ $TAG.$2.02.$1.$3 false
    Rule          $time_local ^(\d{2})/Mar/(\d{4}):(\d{2}):.*$ $TAG.$2.03.$1.$3 false
    Rule          $time_local ^(\d{2})/Apr/(\d{4}):(\d{2}):.*$ $TAG.$2.04.$1.$3 false
    Rule          $time_local ^(\d{2})/May/(\d{4}):(\d{2}):.*$ $TAG.$2.05.$1.$3 false
    Rule          $time_local ^(\d{2})/Jun/(\d{4}):(\d{2}):.*$ $TAG.$2.06.$1.$3 false
    Rule          $time_local ^(\d{2})/Jul/(\d{4}):(\d{2}):.*$ $TAG.$2.07.$1.$3 false
    Rule          $time_local ^(\d{2})/Aug/(\d{4}):(\d{2}):.*$ $TAG.$2.08.$1.$3 false
    Rule          $time_local ^(\d{2})/Sep/(\d{4}):(\d{2}):.*$ $TAG.$2.09.$1.$3 false
    Rule          $time_local ^(\d{2})/Oct/(\d{4}):(\d{2}):.*$ $TAG.$2.10.$1.$3 false
    Rule          $time_local ^(\d{2})/Nov/(\d{4}):(\d{2}):.*$ $TAG.$2.11.$1.$3 false
    Rule          $time_local ^(\d{2})/Dec/(\d{4}):(\d{2}):.*$ $TAG.$2.12.$1.$3 false
    Emitter_Name  re_emitted_error
