[INPUT]
    Name                  syslog
    Tag                   provost.raw
    Mode                  unix_udp
    Path                  /var/run/provost/fluent-bit.sock
    parser                syslog-rfc3164
    unix_perm             0666
    storage.type          filesystem
    Mem_Buf_Limit         32MB