[INPUT]
    Name          tcp
    Tag           provost.error
    Listen        0.0.0.0
    Port          5140
    Format        none
    storage.type  filesystem
    Mem_Buf_Limit         32MB

[INPUT]
    Name          tcp
    Tag           provost.direct
    Listen        0.0.0.0
    Port          5141
    Format        json
    storage.type  filesystem
    Mem_Buf_Limit 32MB
