[OUTPUT]
    Name      file
    Match     provost.access.*
    Path      /var/log/fluent-bit/storage
    File      access.log
    Format    template
    Template  {message}

[OUTPUT]
    Name      file
    Match     provost.error.*
    Path      /var/log/fluent-bit/storage
    File      error.log
    Format    template
    Template  {message}
