[OUTPUT]
    Name      file
    Match     provost.local.access
    Path      /var/log/fluent-bit/storage
    File      access.log
    Format    template
    Template  {schema_json}

[OUTPUT]
    Name      file
    Match     provost.local.error
    Path      /var/log/fluent-bit/storage
    File      error.log
    Format    template
    Template  {schema_json}
