version: 1.2.3
cache: true

endpoints:
  anthropic:
    apiKey: "${ANTHROPIC_API_KEY}"
    promptCache: true
    models:
      - "claude-3-5-sonnet-20241022"
    fetch: true

  custom:
    - name: "OpenWire"
      apiKey: "${OPENAI_API_KEY}"
      baseURL: "http://llm-provost:8000/v1"
      models:
        default:
          - "gpt-5-mini" # You can set a default, but fetch: true will grab the rest
        #fetch: true

interface:
  mcpServers:
    use: true
    create: false
    share: false
    public: false

mcpServers:
  dummy:
    type: streamable-http
    url: http://llm-provost:8000/mcp/dummy
    headers:
      X-Cognito-User: "{{LIBRECHAT_USER_ID}}"
      X-Conversation-Id: "{{LIBRECHAT_BODY_CONVERSATIONID}}"