version: 1.2.3
cache: true
registration:
  socialLogins: ["openid"]

endpoints:
#   anthropic:
#     apiKey: "${ANTHROPIC_API_KEY}"
#     promptCache: true
#     models:
#       - "claude-3-5-sonnet-20241022"
#     fetch: true

  custom:
    - name: "OpenWire"
      apiKey: "${OPENAI_API_KEY}"
      baseURL: "http://llm-provost:8000/llm/openwire/v1"
      headers:
        X-Conversation-Id: "{{LIBRECHAT_BODY_CONVERSATIONID}}"
        X-Cognito-User: "{{LIBRECHAT_USER_ID}}"
      models:
        default:
          - "gpt-5-mini"
        fetch: true

    - name: "Ollama"
      apiKey: "${OLLAMA_API_KEY}"
      baseURL: "http://llm-provost:8000/llm/ollama/v1"
      headers:
        X-Conversation-Id: "{{LIBRECHAT_BODY_CONVERSATIONID}}"
        X-Cognito-User: "{{LIBRECHAT_USER_ID}}"
      models:
        default:
          - "llama3.1:8b"
        fetch: true
    
interface:
  mcpServers:
    use: true
    create: false
    share: false
    public: false

mcpServers:
  atlassian:
    type: sse
    url: https://mcp.atlassian.com/v1/sse


    #  dummy:
#    type: streamable-http
#    url: http://llm-provost:8000/mcp/dummy
#    headers:
#      X-Cognito-User: "{{LIBRECHAT_USER_EMAIL}}"
#      X-Conversation-Id: "{{LIBRECHAT_BODY_CONVERSATIONID}}"

  
