[SERVICE]
    Flush                 1
    Daemon                Off
    Log_Level             info
    Parsers_File          /fluent-bit/etc/parsers.conf
    storage.path          /var/log/fluent-bit/storage
    storage.sync          full
    storage.checksum      On
    storage.backlog.mem_limit 64M

@INCLUDE conf.d/input-syslog.conf
@INCLUDE conf.d/input-tcp-audit.conf
@INCLUDE conf.d/filter-rewrite-tag.conf
@INCLUDE conf.d/filter-parse-access.conf
@INCLUDE conf.d/filter-parse-error.conf
@INCLUDE conf.d/filter-enrich.conf
@INCLUDE conf.d/filter-append-hour.conf
@INCLUDE conf.d/output-local-file.conf
@INCLUDE conf.d/output-s3.conf
